<?php

/**
 * Netherlands: postal code prefix (2 digits) → Province code.
 *
 * Source: PostNL postcode ranges.
 */
return [
    '10' => 'NH', // Noord-Holland (Amsterdam)
    '11' => 'NH',
    '12' => 'NH',
    '13' => 'NH',
    '14' => 'NH',
    '15' => 'NH',
    '16' => 'NH',
    '17' => 'NH',
    '18' => 'FR', // Friesland
    '19' => 'NH',
    '20' => 'ZH', // Zuid-Holland (Den Haag)
    '21' => 'ZH',
    '22' => 'ZH',
    '23' => 'ZH',
    '24' => 'ZH',
    '25' => 'ZH',
    '26' => 'ZH',
    '27' => 'ZH',
    '28' => 'ZH',
    '29' => 'ZH',
    '30' => 'ZH', // Zuid-Holland (Rotterdam)
    '31' => 'UT',
    '32' => 'UT',
    '33' => 'GE', // Gelderland
    '34' => 'UT',
    '35' => 'UT',
    '36' => 'GE',
    '37' => 'GE',
    '38' => 'GE',
    '39' => 'GE',
    '40' => 'GE',
    '41' => 'NB', // Noord-Brabant
    '42' => 'NB',
    '43' => 'NB',
    '44' => 'ZE', // Zeeland
    '45' => 'ZE',
    '46' => 'NB',
    '47' => 'NB',
    '48' => 'NB',
    '49' => 'NB',
    '50' => 'NB',
    '51' => 'NB',
    '52' => 'NB',
    '53' => 'NB',
    '54' => 'LI', // Limburg
    '55' => 'LI',
    '56' => 'NB',
    '57' => 'LI',
    '58' => 'LI',
    '59' => 'LI',
    '60' => 'LI',
    '61' => 'LI',
    '62' => 'LI',
    '63' => 'LI',
    '64' => 'GE',
    '65' => 'GE',
    '66' => 'GE',
    '67' => 'GE',
    '68' => 'GE',
    '69' => 'GE',
    '70' => 'OV', // Overijssel
    '71' => 'OV',
    '72' => 'OV',
    '73' => 'OV',
    '74' => 'OV',
    '75' => 'OV',
    '76' => 'OV',
    '77' => 'OV',
    '78' => 'OV',
    '79' => 'DR', // Drenthe
    '80' => 'FL', // Flevoland
    '81' => 'FL',
    '82' => 'FL',
    '83' => 'FR',
    '84' => 'FR',
    '85' => 'FR',
    '86' => 'FR',
    '87' => 'FR',
    '88' => 'FR',
    '89' => 'DR',
    '90' => 'GR', // Groningen
    '91' => 'GR',
    '92' => 'GR',
    '93' => 'DR',
    '94' => 'DR',
    '95' => 'GR',
    '96' => 'GR',
    '97' => 'GR',
    '98' => 'DR',
    '99' => 'DR',
];
